version: '3.0'
services:
  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres      
    ports:
      - 5435:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - db

  nest-intro:
    image: nest-intro:latest
    build: 
      context: .
    ports:
      - 3030:3000
    depends_on: 
      - db
